print 'Print my name Poelee directly line by line'
print '####   # # #  #####  #      #####  #####'
print '#   #  #   #  #      #      #      #    '
print '####   #   #  #####  #      #####  #####'
print '#      #   #  #      #      #      #    '
print '#      # # #  #####  #####  #####  #####'
